Use this notebook to try to get global eta working as an input to phi instead of F - have to get it in the right format first!

In [1]:
import numpy as np

First: toy example

In [2]:
rand = np.random.normal(size = (1000,1))
rand.shape

(1000, 1)

In [3]:
repeat =np.repeat(rand, 100, axis=1)
repeat.shape

(1000, 100)

In [4]:
final = np.expand_dims(repeat, 2)
final.shape

(1000, 100, 1)

In [5]:
rand #so the one means each value is its own array

array([[-1.86599425e+00],
       [-6.86213413e-01],
       [-2.17962145e-01],
       [-8.13952170e-02],
       [-5.44796764e-01],
       [-8.45574338e-01],
       [ 3.34365349e-01],
       [ 1.84624265e+00],
       [ 1.11826131e+00],
       [ 5.68705193e-01],
       [ 1.01307549e+00],
       [-2.58508115e-01],
       [ 5.26126399e-01],
       [ 7.60566723e-01],
       [ 1.18564986e+00],
       [-1.90955766e+00],
       [ 2.16634614e+00],
       [ 3.23726817e-01],
       [ 3.43541133e-02],
       [ 8.06961836e-02],
       [-4.50082728e-01],
       [ 9.84004379e-01],
       [ 1.23909657e+00],
       [-6.64090867e-01],
       [ 3.43046221e-01],
       [ 1.36829844e+00],
       [ 3.36703922e-01],
       [ 3.57681341e-02],
       [-3.85486950e-02],
       [-1.68436716e-01],
       [-1.28944703e+00],
       [-5.63068801e-01],
       [ 4.13202860e-01],
       [-9.06010190e-01],
       [ 1.83853261e-02],
       [-3.17211532e-01],
       [ 1.22211672e-01],
       [-8.64049021e-01],
       [ 4.3

In [6]:
repeat[0] #so duplicates each entry 100 times!!******

array([-1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86599425,
       -1.86599425, -1.86599425, -1.86599425, -1.86599425, -1.86

In [7]:
final[0] #ah and this just turns each value into its own array

array([[-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1.86599425],
       [-1

In [8]:
#load up data
pipm_med = np.load('/fast_scratch/atlas_images/v01-45/pipm_medium.npz')
pi0_med = np.load('/fast_scratch/atlas_images/v01-45/pi0_medium.npz')

In [9]:
clus_eta_pipm = pipm_med['clus_eta']
clus_eta_pi0 = pi0_med['clus_eta']


In [59]:
pipm_list = ['/fast_scratch/atlas_images/v01-45/pipm_medium.root']
i=0
for pipm_file in pipm_list:
    print(i)
    i+=1
    tree = ur.open(pipm_file)['EventTree']
    cell_e  = gu.loadArrayBranchFlat('cluster_cell_E', tree, 2000)

0


In [56]:
import graph_util as gu
import uproot as ur


In [61]:
cell_e.shape

(672281, 2000)

In [63]:
clus_e   = gu.loadVectorBranchFlat('cluster_E', tree)
    

In [64]:
e_mask = clus_e > 0.5
cell_e = np.nan_to_num(np.log(cell_e), posinf = 0, neginf=0)

<ipython-input-64-95a9062ff3bd>:2: RuntimeWarning: divide by zero encountered in log
  cell_e = np.nan_to_num(np.log(cell_e), posinf = 0, neginf=0)


In [65]:
cell_e = cell_e[e_mask]

In [66]:
cell_e.shape

(592857, 2000)

In [67]:
celle0 = np.where(cell_e==0, 0., cell_e)

In [69]:
celle0

array([[ 1.57021536e+00,  8.30626180e-01,  4.14356227e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.50638840e-01, -3.47037088e+00, -3.84146948e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.54035648e-03, -4.62181785e+00, -1.88327343e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-7.58293822e-01, -2.09791518e+00, -2.41852503e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.44618396e-01, -4.82649426e+00, -4.27391674e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.86923889e+00,  3.85732821e+00,  2.47646621e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [70]:
repeat_eta = np.where(cell_e==0, 0., cell_e)

In [10]:
eta = clus_eta_pipm.reshape(592857,1)

In [11]:
eta.shape

(592857, 1)

In [12]:
repeat_eta = np.repeat(eta, 2000, axis=1)

In [13]:
X_pipm = pipm_med['X']

In [14]:
X_pipm.shape

(592857, 2000, 4)

In [15]:
repeat_eta.shape

(592857, 2000)

In [71]:
eta_exp = np.expand_dims(repeat_eta, 2)

In [17]:
eta_exp.shape

(592857, 2000, 1)

In [18]:
X_pipm[0].shape

(2000, 4)

In [72]:
together = np.concatenate((X_pipm, eta_exp), axis=2)

In [73]:
together.shape

(592857, 2000, 5)

In [74]:
together

array([[[ 1.57021536e+00,  1.37116909e-02,  9.04369354e-03,
          2.00000000e-01,  1.57021536e+00],
        [ 8.30626180e-01,  1.36827230e-02, -1.55043602e-02,
          2.00000000e-01,  8.30626180e-01],
        [ 4.14356227e-01,  1.37407780e-02,  3.35907936e-02,
          2.00000000e-01,  4.14356227e-01],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00]],

       [[-7.50638840e-01, -4.61663604e-02,  1.14724636e-02,
          2.00000000e+00, -7.50638840e-01],
        [-3.47037088e+00, -4.61663604e-02,  6.19648314e+00,
          2.00000000e+00, -3.47037088e+00],
        [-3.84146948e+00, -2.45345652e-01,  1.14724636e-02,
          2.00000000e+00, -3.84146948e+00],
        ...,
        [ 0.00000000e+00,  0.0000000

In [23]:
zeros = X_pipm[0] == 0
zeros

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
etawithzeros = np.where(zeros, 0., eta_exp) #??

In [26]:
zeros.shape

(2000, 4)

In [32]:
etawithzeros.shape

(592857, 2000, 4)

In [40]:
zewor = X_pipm.T[0][0] == 0

In [47]:
R = np.where(zewor, 0., eta_exp.T)

In [53]:
R[0][0]

array([-1.125384  , -0.9594247 ,  0.93537796, ...,  1.3647442 ,
        1.1146117 ,  0.51504624], dtype=float32)